theme: jekyll-theme-modernist
title: Tori's Portfolio Landing Page
description: Welcome to my design portfolio! Here, you'll find documentation and plans for personal projects ranging from hardware to web development.
